export const FETCH_USERS_INPROGRESS="FETCH_USERS_INPROGRESS";
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR="FETCH_USERS_ERROR";

export const SEARCH_USER_INPROGRESS="SEARCH_USER_INPROGRESS";
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS";
export const SEARCH_USER_ERROR="SEARCH_USER_ERROR";

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const LOGOUT="LOGOUT";

export const HISTORY_REQUEST="HISTORY_REQUEST";
export const HISTORY_SUCCESS="HISTORY_SUCCESS";
export const HISTORY_FAILURE="HISTORY_FAILURE";

export const MESSAGE_SUCCESS="MESSAGE_SUCCESS";
export const MESSAGE_ERROR="MESSAGE_ERROR";
export const MESSAGE_CLEAR="MESSAGE_CLEAR";