export const FETCH_LOGGED_USER_INPROGRESS="FETCH_LOGGED_USER_INPROGRESS";
export const FETCH_LOGGED_USER_SUCCESS="FETCH_LOGGED_USER_SUCCESS";
export const FETCH_LOGGED_USER_ERROR="FETCH_LOGGED_USER_ERROR";
